sponsorship:
  - nick: m*i
    money: 100.00
    desc: 加油鸭
  - nick: Timmy
    money: 10.00
    desc: —
  - nick: alpacabro
    money: 6.66
    desc: 高考加油！
  - nick: 匿名者
    money: 16.67
    desc: 同为高三，望大学相见
  - nick: L*s
    money: 99.00
    desc: 莫反的文章不错，加油
  - nick: s*r
    money: 28.88
    desc: 望不忘初心，继续努力
  - nick: G*e
    money: 20.00
    desc: 请你的下午茶~
  - nick: "*师"
    money: 32.30
    desc: 网站很有趣，人应当也很有趣吧
  - nick: "**烨"
    money: 11.45
    desc: 加油鸭

lab:
  - name: Artificial Intelligence
    url: https://ai.xecades.xyz/
    desc: BP 神经网络数字识别可视化
  - name: TIY
    url: https://tiy.xecades.xyz/
    desc: 在线运行 HTML 代码
  - name: Postcard API
    url: https://api.xecades.xyz/
    desc: 个人身份卡片 API 及生成器
  - name: hexo-tag-tiy
    url: https://github.com/Xecades/hexo-tag-tiy
    desc: Hexo 内嵌 TIY
  - name: Fourier Transform
    url: /lab/Fourier/
    desc: 傅里叶级数绘图可视化
  - name: Cube Simulator
    url: /lab/Cube/
    desc: 魔方模拟器
  - name: Gravitation Simulator
    url: /lab/Gravitation/
    desc: 二维星体运动模拟器
  - name: Sort
    url: /lab/Sort/
    desc: 排序算法可视化

friend:
  - nick: Mivik
    url: https://mivik.gitee.io/
    desc: 兴趣使然のProgrammer
  - nick: 甘小蔗
    url: https://gxzv.com/
    desc: “一株情感延迟的全栈工程蔗”
  - nick: GZTime
    url: https://blog.gzti.me/
    desc: Walking on the Time Axis
  - nick: FFox
    url: https://frightenedfoxcn.github.io/notes/
    desc: “不知道在学什么的老学长”

timeline:
  - year: 2016
    meta: [
        { date: "上半年",               desc: "首次接触 C 语言" },
        { date: "9 月 19 日 13:53",     desc: "注册第一个 OJ：openjudge" },
        { date: "9 月 29 日",           desc: "提交第一个程序 超级玛丽 (但是 WA 了)" },
        { date: "9 月 29 日",           desc: "第一次 AC 题目" },
        { date: "10 月 8 日",           desc: "AC 超级玛丽" },
        { date: "10 月 8 日",           desc: "完成 openjudge 的 1.1 全部题目" },
        { date: "下半年",               desc: "学习 C++" },
      ]
  - year: 2017
    meta: [
        { date: "上半年",               desc: "暂时中断 OI 学习" },
        { date: "上半年",               desc: "完全从 C 转入 C++" },
        { date: "10 月 14 日 14:30",    desc: "NOIP2017 普及组初赛" },
        { date: "10 月 18 日 13:54",    desc: "注册洛谷账号" },
        { date: "11 月",                desc: "惊喜地得知进入复赛" },
        { date: "11 月 11 日",          desc: "NOIP2017 普及组复赛" },
      ]
  - year: 2018
    meta: [
        { date: "上半年",               desc: "学了一些 MFC" },
        { date: "上半年",               desc: "认识到 OI 重要性" },
        { date: "上半年",               desc: "继续学习信竞" },
        { date: "8 月",                 desc: "选择还是考普及组" },
        { date: "10 月 13 日 14:30",    desc: "NOIP2018 普及组初赛" },
        { date: "11 月 10 日",          desc: "NOIP2018 普及组复赛" },
        { date: "12 月",                desc: "OI 终于被父母认可" },
      ]
  - year: 2019
    meta: [
        { date: "3 月 11 日",           desc: "签约东辰" },
        { date: "3 月 14 日",           desc: "签约绵中" },
        { date: "6 月 16 日",           desc: "成都七中自主招生考试" },
        { date: "6 月 18 日左右",        desc: "成都七中录取通知" },
        { date: "7 月",                 desc: "跟着七中的叶老学信息学" },
        { date: "8 月",                 desc: "大幅度更新博客" },
        { date: "8 月 31 日",           desc: "成都七中开学" },
        { date: "11 月 16 日",          desc: "CSP-S 2019 复赛" },
      ]
  - year: 2020
    meta: [
        { date: "寒假",                 desc: "学习 npm、nodejs、web、vue" },
        { date: "寒假",                 desc: "大幅更新 / 重构博客" },
        { date: "补充",                 desc: "初识人工智能，编写其可视化程序" },
        { date: "补充",                 desc: "完成 TIY 网页编辑器，里程碑式的进展" },
        { date: "10 月",                desc: "初识傅里叶级数变换，编写其模拟程序" },
        { date: "11 月",                desc: "数学真有意思" },
        { date: "12 月",                desc: "学了一点群论" },
        { date: "12 月",                desc: "学习 Latex 的 tikz 库，终于可以清爽地绘图了！" },
      ]
  - year: 2021
    meta: [
        { date: "1 月",                 desc: "大幅重构博客，「大道至简」" },
        { date: "2 月 1 日",            desc: "DFT，IDFT 和 FFT！" },
        { date: "2 月",                 desc: "博客全部迁移至 vercel，采用 CI 部署" },
        { date: "3 月",                 desc: "自己写的第一个 api 破一万调用" },
        { date: "3 月 17 日",           desc: "学习偏导、隐式方程绘制" },
        { date: "3 月",                 desc: "在阿里云试用了一个月的 ecs" },
        { date: "4 月",                 desc: "重新开始玩几年前买的树莓派" },
        { date: "6 月 7 日",            desc: "高二提前高考" },
        { date: "暑假",                 desc: "第一个摆脱了电脑的暑假" },
        { date: "补充",                 desc: "新爱好：Engraver's Script 英文书法" },
      ]
  - year: 2022
    meta: [
        { date: "这一年",                desc: "高考年" },
        { date: "4 月 18 日白天",        desc: "在 16 岁提前到来的成人礼" },
        { date: "4 月 18 日晚上",        desc: "换掉了用了 7 年的头像" },
        { date: "6 月 7 日",            desc: "高考" },
        { date: "8 月 15 日",           desc: "复读" },
      ]
  - year: 2023
    meta: [
        { date: "6 月 7 日",            desc: "高考" },
        { date: "6 月 23 日",           desc: "出分" },
        { date: "7 月 22 日",           desc: "录取" },
        { date: "8 月 24 日",           desc: "浙江大学竺可桢学院图灵班就读" },
        { date: "8 月",                 desc: "十八岁生日快乐！" },
        { date: "12 月 31 日",          desc: "和朋友参加学校的跨年活动，最快乐的时光" },
      ]
  # - year: 2024
  #   meta: [
  #       { date: "这一年",               desc: "故事还在书写" },
  #     ]